plugins: rubocop-rails
AllCops:
  EnabledByDefault: true
Style/Copyright:
  Enabled: false
  AutocorrectNotice: "Copyright 2025 Mind"
Lint/ConstantResolution:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Bundler/GemComment:
  Enabled: false
Bundler/GemVersion:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/RequireOrder:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Rails/SchemaComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Rails/ReversibleMigrationMethodDefinition:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/InverseOf:
  Enabled: false
