version: "3.7"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis-socialhub

  mysql:
    image: mysql:8.0
    container_name: mysql-socialhub
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: socialhub_development
      MYSQL_USER: socialhub
      MYSQL_PASSWORD: socialhub_password
